---
title: "paiwan"
output: html_document
date: "2023-08-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## R Markdown

```{r}
library(readr)
paiwan_caus <- read_csv("C:/Users/maochang/Desktop/Paiwan causatives/paiwan_caus.csv")
```


```{r}
library(dplyr)
paiwan_caus <- paiwan_caus %>%
  select(Affix, Trans, Type) %>%
  na.omit()

```


```{r}
pa = filter(paiwan_caus, Affix=='pa')
paka = filter(paiwan_caus, Affix=='paka')
pape = filter(paiwan_caus, Affix=='pape')

paka = rbind(paka, paka)
pape = rbind(pape, pape)

all = rbind(pa, paka, pape)

```


```{r}
library(Rling); library(rms); library(visreg); library(car)
library(mlogit); library(polytomous)

all <- all %>%
  mutate(Affix = factor(Affix, level=c('paka', 'pape', 'pa')),
         Trans = factor(Trans),
         Type = factor(Type, level=c('volitional', 'affective', 'physical', 'inducive')))

all1 <- mlogit.data(all, shape = "wide", choice = "Affix")

```

```{r}
m.lrm <- lrm(Affix ~ Trans + Type, data = all)
m.lrm
```
```{r}
m.glm <- glm(Affix ~ Trans + Type, family=binomial, data = all)
m.glm
```

```{r}

influencePlot(m.glm, id = "identify")
```
```{r}
all[c(53, 147, 202, 204), ]
```

```{r}
m.lrm1 <- lrm(Affix ~ Trans + Type, data = all, x = T, y = T)
validate(m.lrm1, B = 200)
```

```{r}
visreg (m.glm, "Trans")
```


```{r}

visreg (m.glm, "Type")

```


```{r}
m1 <- mlogit(Affix ~ 1 | Type + Trans, data = all1, reflevel = "pa")

summary(m1)
```

```{r}
m2 <- polytomous(Affix ~ Type + Trans, data = all)

summary(m2)$statistics
```
```{r}
print(summary(m2), parameter= "logodds")
```
```{r}
round(m2$p.values, 3)
```

